"""
lookup_loader.py

Loads lookup CSV files generated by lookup_builder.py
and provides easy access throughout the project.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict

import pandas as pd


class LookupLoader:
    """
    Loads all lookup CSVs from datasets/lookup.

    Example:
        loader = LookupLoader()

        districts = loader.get("districts")
        occupations = loader.get("occupations")
    """

    def __init__(self) -> None:
        self.lookup_path = (
            Path(__file__).resolve().parents[2]
            / "datasets"
            / "lookup"
        )

        self.tables: Dict[str, pd.DataFrame] = {}

    def load_all(self) -> None:
        """Load every lookup CSV file."""

        if not self.lookup_path.exists():
            raise FileNotFoundError(
                f"Lookup folder not found:\n{self.lookup_path}"
            )

        for csv_file in self.lookup_path.glob("*.csv"):
            self.tables[csv_file.stem] = pd.read_csv(csv_file)

        print(f"Loaded {len(self.tables)} lookup tables.")

    def get(self, table_name: str) -> pd.DataFrame:
        """
        Return a lookup table.

        Example:
            loader.get("districts")
        """

        if table_name not in self.tables:
            raise KeyError(f"Lookup table '{table_name}' not loaded.")

        return self.tables[table_name]

    def list_tables(self):
        """Return all loaded lookup table names."""
        return sorted(self.tables.keys())

    def reload(self):
        """Reload lookup tables."""
        self.tables.clear()
        self.load_all()


# Singleton instance
lookup_loader = LookupLoader()


if __name__ == "__main__":
    lookup_loader.load_all()

    print("\nAvailable Tables:")
    print("-----------------")

    for table in lookup_loader.list_tables():
        print(table)