import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import {
  BookOpen,
  UserCheck,
  FileText,
  ShieldAlert,
  MapPin,
  CheckCircle2,
  Clock,
  ArrowRight,
  Network,
  Database,
  AlertTriangle,
  Sparkles,
  Save,
  Send,
  X,
  Check
} from 'lucide-react'

interface OfficerDiaryProps {
  firNumber: string
  officerName: string
}

interface TimelineEntry {
  time: string
  type: string
  summary: string
  icon: 'user' | 'file' | 'shield' | 'map' | 'book'
}

interface EvidenceAsset {
  name: string
  type: string
  date: string
  status: 'Verified' | 'Pending Sign' | 'Unverified' | 'Active'
}

export function OfficerDiary({ firNumber, officerName }: OfficerDiaryProps) {
  const navigate = useNavigate()
  const [noteTitle, setNoteTitle] = useState('')
  const [noteText, setNoteText] = useState('')
  const [isSaving, setIsSaving] = useState(false)
  const [toastMsg, setToastMsg] = useState('')
  const [showDailyBrief, setShowDailyBrief] = useState(false)

  const showToast = (msg: string) => {
    setToastMsg(msg)
    setTimeout(() => setToastMsg(''), 3000)
  }

  const handleFinalReport = () => {
    const doc = new jsPDF()
    doc.setFontSize(16)
    doc.setTextColor(37, 99, 235)
    doc.text(`INVESTIGATION TIMELINE - ${firNumber}`, 14, 20)
    
    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text(`Generated by: ${officerName} | Date: ${new Date().toLocaleDateString()}`, 14, 28)
    
    const tableData = timeline.map(entry => [
      entry.time,
      entry.type,
      entry.summary
    ])
    
    autoTable(doc, {
      startY: 35,
      head: [["Time", "Type", "Summary"]],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [241, 245, 249] }
    })
    
    doc.save(`final_report_${firNumber}.pdf`)
  }

  // Timeline entries list state
  const [timeline, setTimeline] = useState<TimelineEntry[]>([
    { time: '03:15 PM', type: 'Location Verified', summary: 'Resident coordinates at J.C. Nagar Sector 4 successfully mapped via tower records.', icon: 'map' },
    { time: '01:40 PM', type: 'Suspect Identified', summary: 'Accused Ravi Kumar linked to active geolocation proximity indices.', icon: 'shield' },
    { time: '11:10 AM', type: 'Evidence Uploaded', summary: 'Security footage matching suspect vehicle KA01AB1234 uploaded to central registry.', icon: 'file' },
    { time: '09:30 AM', type: 'Witness Interview Completed', summary: 'Interviewed Suresh Babu regarding morning timelines and vehicle sightings.', icon: 'user' }
  ])

  // Progress Tracker stages
  const progressStages = [
    { label: 'Case Registered', desc: 'FIR lodged in system', status: 'completed' },
    { label: 'Evidence Collection', desc: 'Forensics & media uploaded', status: 'completed' },
    { label: 'Suspect Identification', desc: 'AI association mapped', status: 'completed' },
    { label: 'Analysis', desc: 'Pattern and vector checks active', status: 'active' },
    { label: 'Report Generation', desc: 'Dossier compiling ready', status: 'pending' },
    { label: 'Case Closure', desc: 'Final charge sheet submitted', status: 'pending' }
  ]

  // Suggested next step chips
  const suggestedSteps = [
    'Interview Witness Suresh Babu',
    'Verify Vehicle KA01AB1234',
    'Compare Similar Burglaries',
    'Generate Criminal Network',
    'Request tower cell trace logs'
  ]

  // Linked evidence cards
  const linkedAssets: EvidenceAsset[] = [
    { name: 'FIR Primary Record', type: 'PDF Document', date: '12-May-2026', status: 'Active' },
    { name: 'Witness Suresh Statement', type: 'DOCX Sheet', date: '13-May-2026', status: 'Pending Sign' },
    { name: 'Patio Window Glass Casts', type: 'Image JPG', date: '12-May-2026', status: 'Verified' },
    { name: 'Mobile Tower Intersection', type: 'CSV Logs', date: '14-May-2026', status: 'Unverified' }
  ]

  const handleLogNote = () => {
    if (!noteText.trim()) return

    const now = new Date()
    const formattedTime = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    const entryTitle = noteTitle.trim() || 'Officer Investigation Update'

    const newEntry: TimelineEntry = {
      time: formattedTime,
      type: entryTitle,
      summary: noteText.trim(),
      icon: 'book'
    }

    // Prepend to timeline
    setTimeline((prev) => [newEntry, ...prev])

    // Clear inputs and simulate auto-save triggers
    setNoteTitle('')
    setNoteText('')
    setIsSaving(true)
    setTimeout(() => setIsSaving(false), 900)
  }

  const getTimelineIcon = (iconName: string) => {
    switch (iconName) {
      case 'user': return <UserCheck className="h-4.5 w-4.5 text-[#2563EB]" />
      case 'file': return <FileText className="h-4.5 w-4.5 text-[#60A5FA]" />
      case 'shield': return <ShieldAlert className="h-4.5 w-4.5 text-[#EF4444]" />
      case 'map': return <MapPin className="h-4.5 w-4.5 text-[#F59E0B]" />
      default: return <BookOpen className="h-4.5 w-4.5 text-[#A78BFA]" />
    }
  }

  const getStatusBadgeClass = (status: string) => {
    switch (status) {
      case 'Verified': return 'bg-[#2563EB]/15 text-[#2563EB] border-[#2563EB]/25'
      case 'Pending Sign': return 'bg-[#F59E0B]/15 text-[#F59E0B] border-[#F59E0B]/25'
      case 'Active': return 'bg-[#2563EB]/15 text-[#2563EB] border-[#2563EB]/25'
      default: return 'bg-gray-800 text-gray-400 border-white/5'
    }
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-10 gap-6 items-stretch pt-2 select-none">
      
      {/* LEFT COLUMN: Notes Editor & Timeline logs (col-span-6) */}
      <div className="col-span-1 lg:col-span-6 space-y-6">
        
        {/* Editor Box */}
        <div className="bg-[#111827] border border-[rgba(255,255,255,0.06)] rounded-xl p-6 shadow-sm">
          {/* Header */}
          <div className="flex justify-between items-start mb-5 border-b border-[rgba(255,255,255,0.04)] pb-3">
            <div>
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">Officer Investigation Diary</h3>
              <p className="text-[10px] text-[#94A3B8]/60 uppercase tracking-widest mt-0.5">
                Case logs, evidence observations and AI-assisted case documentation
              </p>
            </div>
            <div className="flex items-center gap-1.5 text-[8.5px] font-mono text-[#94A3B8]/40">
              <span className="h-1.5 w-1.5 rounded-full bg-[#2563EB] animate-pulse" />
              <span>{isSaving ? 'AUTO-SAVING...' : 'JOURNAL SYNCED'}</span>
            </div>
          </div>

          {/* Form Fields */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4 text-[10px] select-none font-sans">
            <div>
              <span className="text-[#94A3B8]/40 font-mono uppercase tracking-widest block">Active Case Target</span>
              <span className="text-white font-extrabold mt-1 block bg-[#0B1220] border border-white/5 px-2.5 py-1.5 rounded-lg truncate">
                {firNumber}
              </span>
            </div>
            <div>
              <span className="text-[#94A3B8]/40 font-mono uppercase tracking-widest block">Investigating Officer</span>
              <span className="text-white font-bold mt-1 block bg-[#0B1220] border border-white/5 px-2.5 py-1.5 rounded-lg truncate">
                {officerName}
              </span>
            </div>
            <div>
              <span className="text-[#94A3B8]/40 font-mono uppercase tracking-widest block">System Timestamp</span>
              <span className="text-[#94A3B8] font-bold mt-1 block bg-[#0B1220] border border-white/5 px-2.5 py-1.5 rounded-lg">
                {new Date().toLocaleString([], { dateStyle: 'short', timeStyle: 'short' })}
              </span>
            </div>
          </div>

          {/* Text fields */}
          <div className="space-y-3.5">
            <input
              type="text"
              placeholder="Entry Title (e.g. Witness Suresh interview brief)"
              value={noteTitle}
              onChange={(e) => setNoteTitle(e.target.value)}
              className="w-full bg-[#0B1220] border border-[rgba(255,255,255,0.06)] rounded-lg text-xs font-semibold text-white px-3.5 py-2.5 outline-none focus:border-[#2563EB] placeholder-[#94A3B8]/35 transition-colors"
            />
            <textarea
              placeholder="Write investigation updates, field records, and observation notes here. Auto-saved locally..."
              value={noteText}
              onChange={(e) => setNoteText(e.target.value)}
              rows={4}
              className="w-full bg-[#0B1220] border border-[rgba(255,255,255,0.06)] rounded-lg text-xs font-medium text-[#E2E8F0] px-3.5 py-2.5 outline-none focus:border-[#2563EB] placeholder-[#94A3B8]/35 transition-colors resize-none custom-scrollbar"
            />
          </div>

          {/* Log button */}
          <div className="flex justify-end mt-4">
            <button
              onClick={handleLogNote}
              disabled={!noteText.trim()}
              className="flex items-center gap-1.5 bg-[#2563EB] hover:bg-[#1D4ED8] disabled:bg-gray-800 disabled:opacity-40 disabled:cursor-not-allowed text-white font-bold text-[10px] tracking-wider uppercase px-4 py-2.5 rounded-lg transition-colors cursor-pointer outline-none"
            >
              <Send className="h-3.5 w-3.5" />
              <span>Log Entry to Timeline</span>
            </button>
          </div>
        </div>

        {/* Timeline of Entries */}
        <div className="bg-[#111827] border border-[rgba(255,255,255,0.06)] rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between border-b border-[rgba(255,255,255,0.04)] pb-3 mb-5">
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">Chronological Case Journal</h4>
            <span className="text-[8.5px] font-mono text-[#94A3B8]/40 uppercase tracking-widest">
              {timeline.length} Entries Logged
            </span>
          </div>

          <div className="space-y-4">
            {timeline.map((entry, idx) => (
              <div
                key={idx}
                className="flex items-start gap-4 border-l-2 border-[#2563EB]/20 pl-4 py-2 hover:border-[#2563EB]/50 transition-colors animate-fade-in"
              >
                {/* Visual Icon */}
                <div className="h-8.5 w-8.5 rounded-full bg-[#0B1220] border border-white/5 flex items-center justify-center shrink-0 shadow-inner">
                  {getTimelineIcon(entry.icon)}
                </div>

                {/* Event text info */}
                <div className="space-y-1 select-none font-sans text-xs">
                  <div className="flex items-center gap-2">
                    <span className="text-white font-extrabold tracking-wide">{entry.type}</span>
                    <span className="text-[#94A3B8]/45 font-mono text-[9px] flex items-center gap-1">
                      <Clock className="h-2.5 w-2.5" />
                      <span>{entry.time}</span>
                    </span>
                  </div>
                  <p className="text-[#94A3B8] leading-relaxed font-normal">{entry.summary}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* RIGHT COLUMN: Progress tracker & AI highlights (col-span-4) */}
      <div className="col-span-1 lg:col-span-4 space-y-6">
        
        {/* Visual Progress tracker */}
        <div className="bg-[#111827] border border-[rgba(255,255,255,0.06)] rounded-xl p-6 shadow-sm">
          <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-4 border-b border-[rgba(255,255,255,0.04)] pb-2.5">
            Investigation Progress
          </h4>
          
          <div className="space-y-4 relative font-sans text-xs">
            {progressStages.map((stage, idx) => (
              <div key={idx} className="flex items-start gap-3">
                {/* Colored check indicator circle */}
                <div className="flex flex-col items-center">
                  <div className={`h-4.5 w-4.5 rounded-full border flex items-center justify-center text-[9px] font-bold ${
                    stage.status === 'completed'
                      ? 'bg-[#2563EB]/25 border-[#2563EB] text-[#2563EB]'
                      : stage.status === 'active'
                      ? 'bg-[#2563EB]/25 border-[#2563EB] text-[#2563EB] animate-pulse'
                      : 'bg-[#0B1220] border-white/10 text-[#94A3B8]/30'
                  }`}>
                    {stage.status === 'completed' ? '✓' : idx + 1}
                  </div>
                  {idx < progressStages.length - 1 && (
                    <div className={`w-0.5 h-6 my-1 ${
                      stage.status === 'completed' ? 'bg-[#2563EB]/40' : 'bg-white/5'
                    }`} />
                  )}
                </div>

                {/* Stage Info */}
                <div className="-mt-0.5 select-none">
                  <span className={`font-bold block tracking-wide ${
                    stage.status === 'active' ? 'text-[#2563EB]' : 'text-[#F8FAFC]'
                  }`}>
                    {stage.label}
                  </span>
                  <span className="text-[#94A3B8]/60 text-[9.5px] mt-0.5 block">{stage.desc}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* AI Insight Summary & Suggestions */}
        <div className="bg-[#111827] border border-[rgba(255,255,255,0.06)] rounded-xl p-6 shadow-sm space-y-4.5">
          <h4 className="text-xs font-bold text-white uppercase tracking-wider border-b border-[rgba(255,255,255,0.04)] pb-2.5 flex items-center gap-1.5">
            <Sparkles className="h-4 w-4 text-[#2563EB]" />
            <span>AI Assistant Diagnostics</span>
          </h4>

          {/* Summary */}
          <div className="bg-[#2563EB]/5 border border-[#2563EB]/20 rounded-xl p-3.5 select-none">
            <div className="flex items-center gap-1.5 text-[#2563EB] text-[9.5px] font-mono font-bold uppercase tracking-wider mb-1.5">
              <CheckCircle2 className="h-3.5 w-3.5" />
              <span>AI Summary Ready</span>
            </div>
            <p className="text-[10.5px] text-[#94A3B8] leading-relaxed">
              "Today's investigation identified two new witnesses, one possible suspect connection and additional digital evidence requiring further verification."
            </p>
          </div>

          {/* Suggested next steps */}
          <div className="space-y-2">
            <span className="text-[8.5px] font-mono tracking-widest text-[#94A3B8]/50 font-bold uppercase block">
              AI Suggested Next Steps
            </span>
            <div className="flex flex-wrap gap-2">
              {suggestedSteps.map((step) => (
                <button
                  key={step}
                  onClick={() => setNoteText((prev) => prev ? prev + `\n- Follow up: ${step}` : `- Follow up: ${step}`)}
                  className="bg-[#0B1220]/50 border border-[rgba(255,255,255,0.06)] hover:border-[#2563EB]/30 text-[#94A3B8] hover:text-white px-2.5 py-1 rounded-lg text-[9px] transition-all cursor-pointer outline-none"
                >
                  {step}
                </button>
              ))}
            </div>
          </div>

          {/* AI Feature Indicators Panel */}
          <div className="border-t border-[rgba(255,255,255,0.04)] pt-3.5 mt-2 text-[10px] space-y-3 font-sans">
            {/* Risk Assessment */}
            <div className="flex justify-between items-center bg-[#0B1220]/30 border border-white/5 rounded-lg p-2.5">
              <span className="text-[#94A3B8] font-semibold">AI Risk Assessment:</span>
              <span className="text-[#F59E0B] font-bold">Medium Risk Patterns</span>
            </div>

            {/* Missing Info warnings */}
            <div className="flex items-start gap-2.5 bg-[#EF4444]/5 border border-[#EF4444]/20 rounded-lg p-3">
              <AlertTriangle className="h-4.5 w-4.5 text-[#EF4444] shrink-0 mt-0.5" />
              <div className="space-y-0.5">
                <span className="text-white font-extrabold text-[9.5px] tracking-wide block uppercase">AI Missing Information alert</span>
                <p className="text-[#94A3B8] text-[9px] leading-relaxed">
                  Notice: Tower cell traces and suspect mobile location logs are missing for the event window.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Linked Evidence Documents */}
        <div className="bg-[#111827] border border-[rgba(255,255,255,0.06)] rounded-xl p-6 shadow-sm">
          <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-4 border-b border-[rgba(255,255,255,0.04)] pb-2.5">
            Linked Investigation Assets
          </h4>

          <div className="grid grid-cols-1 gap-3">
            {linkedAssets.map((asset) => (
              <div
                key={asset.name}
                className="flex items-center justify-between p-3 bg-[#0B1220]/50 border border-white/5 rounded-lg hover:border-[rgba(37,99,235,0.15)] transition-colors"
              >
                <div>
                  <span className="text-white font-bold text-[10.5px] block">{asset.name}</span>
                  <span className="text-[#94A3B8]/50 text-[8px] font-mono uppercase tracking-wider block mt-0.5">
                    {asset.type} • {asset.date}
                  </span>
                </div>
                <span className={`px-2 py-0.5 border text-[7.5px] font-mono font-bold tracking-wider rounded uppercase ${getStatusBadgeClass(asset.status)}`}>
                  {asset.status}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Quick Actions buttons */}
        <div className="bg-[#111827] border border-[rgba(255,255,255,0.06)] rounded-xl p-6 shadow-sm space-y-3 flex flex-col justify-center">
          <div className="flex items-center justify-between border-b border-[rgba(255,255,255,0.04)] pb-2.5 mb-1.5">
            <span className="text-xs font-bold text-white uppercase tracking-wider">Workspace Controls</span>
          </div>

          <div className="grid grid-cols-2 gap-3 text-[9px] uppercase font-bold tracking-wider">
            {/* Action 1: Save Investigation */}
            <button
              onClick={() => showToast(`Session successfully saved to database.`)}
              className="flex items-center justify-center gap-1.5 bg-[#2563EB] hover:bg-[#1D4ED8] text-white py-2.5 rounded-lg transition-colors cursor-pointer outline-none"
            >
              <Save className="h-3.5 w-3.5" />
              <span>Save Session</span>
            </button>

            {/* Action 2: Generate Daily Report */}
            <button
              onClick={() => setShowDailyBrief(true)}
              className="flex items-center justify-center gap-1.5 bg-[#0B1220] border border-[rgba(255,255,255,0.06)] hover:border-[#2563EB]/40 text-[#94A3B8] hover:text-white py-2.5 rounded-lg transition-colors cursor-pointer outline-none"
            >
              <FileText className="h-3.5 w-3.5 text-[#2563EB]" />
              <span>Daily Brief</span>
            </button>

            {/* Action 3: Generate Final Report */}
            <button
              onClick={handleFinalReport}
              className="flex items-center justify-center gap-1.5 bg-[#0B1220] border border-[rgba(255,255,255,0.06)] hover:border-[#2563EB]/40 text-[#94A3B8] hover:text-white py-2.5 rounded-lg transition-colors cursor-pointer outline-none"
            >
              <CheckCircle2 className="h-3.5 w-3.5 text-[#2563EB]" />
              <span>Final Report</span>
            </button>

            {/* Action 4: Share with Senior Officer */}
            <button
              onClick={() => showToast(`Docket securely dispatched to Superintendent.`)}
              className="flex items-center justify-center gap-1.5 bg-[#0B1220] border border-[rgba(255,255,255,0.06)] hover:border-[#2563EB]/40 text-[#94A3B8] hover:text-white py-2.5 rounded-lg transition-colors cursor-pointer outline-none"
            >
              <UserCheck className="h-3.5 w-3.5 text-[#A78BFA]" />
              <span>Share Docket</span>
            </button>

            {/* Action 5: Open Criminal Network */}
            <button
              onClick={() => navigate('/criminal-network')}
              className="col-span-2 flex items-center justify-center gap-2 bg-[#0B1220] border border-[rgba(255,255,255,0.06)] hover:border-[#2563EB]/40 text-[#94A3B8] hover:text-white py-2.5 rounded-lg transition-colors cursor-pointer outline-none"
            >
              <Network className="h-4 w-4 text-[#2563EB]" />
              <span>Open Criminal Network Graph</span>
              <ArrowRight className="h-3 w-3" />
            </button>

            {/* Action 6: Compare Similar Cases */}
            <button
              onClick={() => navigate('/crime-pattern-similarity')}
              className="col-span-2 flex items-center justify-center gap-2 bg-[#0B1220] border border-[rgba(255,255,255,0.06)] hover:border-[#2563EB]/40 text-[#94A3B8] hover:text-white py-2.5 rounded-lg transition-colors cursor-pointer outline-none"
            >
              <Database className="h-4 w-4 text-[#2563EB]" />
              <span>Compare Similar Cases</span>
              <ArrowRight className="h-3 w-3" />
            </button>
          </div>
        </div>

      </div>

      {/* Daily Brief Modal */}
      {showDailyBrief && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
          <div className="bg-[#0B1220] border border-[#2563EB]/30 rounded-xl shadow-[0_20px_60px_-15px_rgba(0,0,0,0.7)] w-full max-w-md overflow-hidden flex flex-col">
            <div className="flex items-center justify-between p-4 border-b border-[rgba(255,255,255,0.06)] bg-[#121826]/80">
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4 text-[#2563EB]" />
                <h3 className="text-sm font-bold text-white tracking-wide uppercase">Daily Briefing Rules</h3>
              </div>
              <button 
                onClick={() => setShowDailyBrief(false)}
                className="p-1.5 text-[#94A3B8] hover:text-white hover:bg-[#182235] rounded-lg transition-colors cursor-pointer outline-none"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
            <div className="p-6 space-y-4 text-left">
              <ul className="text-xs text-[#94A3B8] space-y-4 font-mono leading-relaxed list-disc list-inside">
                <li><strong className="text-white font-sans uppercase text-[10px]">Verify Source:</strong> Ensure all statements are double-checked against CCTV or physical evidence logs.</li>
                <li><strong className="text-white font-sans uppercase text-[10px]">Update Risk:</strong> Re-calculate AI risk assessment parameters every 12 hours.</li>
                <li><strong className="text-white font-sans uppercase text-[10px]">Trace Comm:</strong> Submit new phone numbers for telecom trace within 1 hour of discovery.</li>
                <li><strong className="text-white font-sans uppercase text-[10px]">Sign Off:</strong> Obtain superintendent's digital signature for all high-severity warrants.</li>
              </ul>
            </div>
            <div className="p-4 border-t border-[rgba(255,255,255,0.06)] bg-[#121826]/50 flex justify-end">
              <button 
                onClick={() => setShowDailyBrief(false)}
                className="px-5 py-2 rounded-lg text-xs font-bold text-white bg-[#2563EB] hover:bg-[#1D4ED8] transition-colors cursor-pointer outline-none"
              >
                Understood
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Success Toast */}
      {toastMsg && (
        <div className="fixed bottom-6 right-6 z-50 animate-slide-up">
          <div className="bg-[#121826]/95 backdrop-blur-md border border-[#22C55E]/30 shadow-[0_8px_30px_rgba(0,0,0,0.4)] rounded-xl p-4 flex items-center gap-3 min-w-[250px]">
            <div className="h-6 w-6 rounded-full bg-[#22C55E]/20 flex items-center justify-center shrink-0 border border-[#22C55E]/40">
              <Check className="h-3.5 w-3.5 text-[#22C55E]" />
            </div>
            <p className="text-[11px] text-white font-bold tracking-wide uppercase">
              {toastMsg}
            </p>
          </div>
        </div>
      )}
    </div>
  )
}

export default OfficerDiary
