export { InvestigationIngestion } from './InvestigationIngestion'
export { FeaturedSimilarCase } from './FeaturedSimilarCase'
export { SimilarityAnalysis } from './SimilarityAnalysis'
export { PatternComparison } from './PatternComparison'
export { SimilarCasesTable } from './SimilarCasesTable'
export { AIInsightCard } from './AIInsightCard'
export { RecommendedActions } from './RecommendedActions'
export type { SimilarityCaseData } from './FeaturedSimilarCase'
export type { MatchingFactor } from './SimilarityAnalysis'
export type { ComparisonAttribute } from './PatternComparison'
